name = "aifindr"
main = ".output/server/index.mjs"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = ".output/public" }

routes = [
  { pattern = "aifindr.org", zone_name = "aifindr.org", custom_domain = true, enabled = true, previews_enabled = false }
]