/**
 * Sync Markdown Content to D1
 * Reads all content/tools/**\/*.md files and generates SQL to upsert into D1.
 * Intended to run in GitHub Actions after content changes on main branch.
 *
 * Usage:
 *   node scripts/sync-to-d1.js                  → prints SQL to stdout
 *   node scripts/sync-to-d1.js --file out.sql   → writes SQL to file
 */

import { readdirSync, readFileSync, existsSync, writeFileSync } from 'fs'
import { join, relative, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const CONTENT_DIR = join(__dirname, '..', 'content', 'tools')

// Lightweight YAML frontmatter parser (avoids dependency on 'yaml' package)
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/)
  if (!match) return null

  const raw = match[1]
  const body = match[2].trim()

  // Simple YAML key-value parser (sufficient for frontmatter)
  const meta = {}
  let currentKey = null
  let currentArray = null

  for (const line of raw.split('\n')) {
    // Array item:   - "value" or - value
    const arrayMatch = line.match(/^\s+-\s+"?([^"]*)"?\s*$/)
    if (arrayMatch && currentArray !== null) {
      currentArray.push(arrayMatch[1])
      continue
    }

    // Key: value
    const kvMatch = line.match(/^(\w[\w_]*):\s*(.*)$/)
    if (kvMatch) {
      currentKey = kvMatch[1]
      const val = kvMatch[2].trim()
      currentArray = null

      if (val === 'true') { meta[currentKey] = true }
      else if (val === 'false') { meta[currentKey] = false }
      else if (val === '' || val === '[]') { meta[currentKey] = null; currentArray = [] }
      else if (/^\d+(\.\d+)?$/.test(val)) { meta[currentKey] = Number(val) }
      else { meta[currentKey] = val.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1') }
    }
  }

  return { meta, body }
}

function findMarkdownFiles(dir) {
  const files = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findMarkdownFiles(fullPath))
    } else if (entry.name.endsWith('.md')) {
      files.push(fullPath)
    }
  }
  return files
}

function esc(str) {
  if (!str) return 'NULL'
  return `'${String(str).replace(/'/g, "''")}'`
}

/** Parse a value that might be a JSON array string (e.g. '["a","b"]') */
function parseArray(val) {
  if (!val || typeof val !== 'string') return val
  const t = val.trim()
  if (t.startsWith('[') && t.endsWith(']')) {
    try { return JSON.parse(t) } catch { return val }
  }
  return val
}

function now() {
  return new Date().toISOString().slice(0, 19).replace('T', ' ')
}

function main() {
  if (!existsSync(CONTENT_DIR)) {
    console.log('-- No content directory found. Skipping sync.')
    return
  }

  const files = findMarkdownFiles(CONTENT_DIR)
  const timestamp = now()
  const lines = []

  lines.push('-- Auto-generated by sync-to-d1.js at ' + timestamp)
  lines.push('')

  for (const filePath of files) {
    const content = readFileSync(filePath, 'utf-8')
    const parsed = parseFrontmatter(content)
    if (!parsed) {
      console.warn(`Skipping ${filePath}: no frontmatter`)
      continue
    }

    const m = parsed.meta
    const body = parsed.body
    const relPath = relative(CONTENT_DIR, filePath)
    const category = relPath.split('/')[0]

    // Normalize JSON-string arrays to real arrays
    const tags = parseArray(m.tags)
    const platformsVal = parseArray(m.platforms) || m.platforms
    const platforms = Array.isArray(platformsVal) ? platformsVal.join(',') : (typeof platformsVal === 'string' ? platformsVal : '')
    const slug = m.slug || (m.name ? m.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') : 'unknown')

    lines.push(`-- ${relPath}`)
    lines.push(`INSERT OR IGNORE INTO tools (`)
    lines.push(`  slug, name, category, website, pricing, price_starting, price_detail,`)
    lines.push(`  has_free_trial, platforms, status, launched, meta_description,`)
    lines.push(`  cover_image, og_image, featured, verified, editor_pick,`)
    lines.push(`  submitter_site, submitter_github, content_path, body,`)
    lines.push(`  use_cases, target_users, data_source, last_verified,`)
    lines.push(`  submitted_at, updated_at`)
    lines.push(`) VALUES (`)
    lines.push(`  ${esc(slug)},`)
    lines.push(`  ${esc(m.name)},`)
    lines.push(`  ${esc(category)},`)
    lines.push(`  ${esc(m.website)},`)
    lines.push(`  ${esc(m.pricing)},`)
    lines.push(`  ${m.price_starting ?? 0},`)
    lines.push(`  ${esc(m.price_detail)},`)
    lines.push(`  ${m.has_free_trial ? 1 : 0},`)
    lines.push(`  ${esc(platforms)},`)
    lines.push(`  ${esc(m.status || 'active')},`)
    lines.push(`  ${esc(m.launched)},`)
    lines.push(`  ${esc(m.meta_description)},`)
    lines.push(`  ${esc(m.cover_image)},`)
    lines.push(`  ${esc(m.og_image)},`)
    lines.push(`  ${m.featured ? 1 : 0},`)
    lines.push(`  ${m.verified ? 1 : 0},`)
    lines.push(`  ${m.editor_pick ? 1 : 0},`)
    lines.push(`  ${esc(m.submitter_site)},`)
    lines.push(`  ${esc(m.submitter_github)},`)
    lines.push(`  ${esc(relPath)},`)
    lines.push(`  ${esc(body)},`)
    // v2.0 新字段
    const ucArr = parseArray(m.use_cases)
    const tuArr = parseArray(m.target_users)
    const useCases = Array.isArray(ucArr) ? ucArr.join(',') : (ucArr || '')
    const targetUsers = Array.isArray(tuArr) ? tuArr.join(',') : (tuArr || '')
    lines.push(`  ${esc(useCases)},`)
    lines.push(`  ${esc(targetUsers)},`)
    lines.push(`  ${esc(m.data_source)},`)
    lines.push(`  ${esc(m.last_verified || timestamp)},`)
    lines.push(`  ${esc(m.submitted_at || timestamp)},`)
    lines.push(`  ${esc(timestamp)}`)
    lines.push(`);`)

    // ── tool_tags ──
    if (Array.isArray(tags) && tags.length > 0) {
      lines.push(`DELETE FROM tool_tags WHERE tool_id = (SELECT id FROM tools WHERE slug = ${esc(slug)});`)
      for (const tag of tags) {
        lines.push(`INSERT INTO tool_tags (tool_id, tag) SELECT id, ${esc(tag)} FROM tools WHERE slug = ${esc(slug)};`)
      }
    }

    // ── tool_images ──
    const images = parseArray(m.images) || m.images
    if (Array.isArray(images) && images.length > 0) {
      lines.push(`DELETE FROM tool_images WHERE tool_id = (SELECT id FROM tools WHERE slug = ${esc(slug)});`)
      images.forEach((img, i) => {
        lines.push(`INSERT INTO tool_images (tool_id, url, alt, caption, sort_order, image_type, width, height)`)
        lines.push(`  SELECT id, ${esc(img.url)}, ${esc(img.alt || '')}, ${esc(img.caption || '')}, ${i}, ${esc(img.type || 'screenshot')}, ${img.width ?? 'NULL'}, ${img.height ?? 'NULL'}`)
        lines.push(`  FROM tools WHERE slug = ${esc(slug)};`)
      })
    }

    // ── tool_videos ──
    const videos = parseArray(m.videos) || m.videos
    if (Array.isArray(videos) && videos.length > 0) {
      lines.push(`DELETE FROM tool_videos WHERE tool_id = (SELECT id FROM tools WHERE slug = ${esc(slug)});`)
      videos.forEach((vid, i) => {
        lines.push(`INSERT INTO tool_videos (tool_id, url, video_id, platform, title, video_type, thumbnail, duration, sort_order)`)
        lines.push(`  SELECT id, ${esc(vid.url)}, ${esc(vid.video_id || '')}, ${esc(vid.platform || 'direct')}, ${esc(vid.title || '')}, ${esc(vid.type || 'demo')}, ${esc(vid.thumbnail || '')}, ${vid.duration ?? 'NULL'}, ${i}`)
        lines.push(`  FROM tools WHERE slug = ${esc(slug)};`)
      })
    }

    lines.push('')
  }

  lines.push('-- Sync complete: ' + files.length + ' files processed')

  const output = lines.join('\n')
  const outFile = process.argv.includes('--file') ? process.argv[process.argv.indexOf('--file') + 1] : null

  if (outFile) {
    writeFileSync(outFile, output)
    console.log(`SQL written to ${outFile}`)
  } else {
    console.log(output)
  }
}

main()
